platform :ios, '9.0'
#use_frameworks!
inhibit_all_warnings!

project 'ヾ(･ε･｀*)'

targetsArray = ['老婆专属的App', '打飞机']

targetsArray.each do |t|
    target t do
        pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
#        pod 'pop', :git => 'https://github.com/facebook/pop.git'
        pod 'pop'
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        puts #{target.name}
    end
    
end

