# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ヾ(･ε･｀*)' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ヾ(･ε･｀*)
  
  pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
  pod 'pop', :git => 'https://github.com/facebook/pop.git'

end
